<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><RootNamespace>WarrantRisk.Api</RootNamespace></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WarrantRisk.Domain\WarrantRisk.Domain.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
</Project>
